"""Per-session CSRF token issuance + validation.

The token is generated by :func:`secrets.token_urlsafe` and stored in
the aiohttp_session for the lifetime of the session. Every state-changing
request must echo it back either as a hidden form field named ``_csrf``
or via the ``X-CSRF-Token`` header (htmx wires this up via ``hx-headers``
in ``base.html``).

Comparisons go through :func:`hmac.compare_digest` to avoid leaking the
token via response timing.
"""

from __future__ import annotations

import secrets
from typing import TYPE_CHECKING

from .auth import constant_time_equals

if TYPE_CHECKING:  # pragma: no cover - hint only
    from aiohttp_session import Session

# Key under which the token lives inside the session payload.
SESSION_KEY = "_csrf_token"

# Form field + header names accepted by the middleware.
FORM_FIELD = "_csrf"
HEADER_NAME = "X-CSRF-Token"


def _new_token() -> str:
    """Return a cryptographically random URL-safe token."""
    return secrets.token_urlsafe(32)


def get_or_create_token(session: Session) -> str:
    """Return the CSRF token for ``session``, creating one if needed."""
    token = session.get(SESSION_KEY)
    if not isinstance(token, str) or not token:
        token = _new_token()
        session[SESSION_KEY] = token
    return token


def validate_token(session: Session, candidate: str | None) -> bool:
    """Return True iff ``candidate`` matches the session's stored token."""
    if not candidate:
        return False
    expected = session.get(SESSION_KEY)
    if not isinstance(expected, str) or not expected:
        return False
    return constant_time_equals(expected, candidate)
